@host=http://localhost:5259

GET  {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4Mjk5MGU3ZS05NWFiLTRiYjktOTdkNy02MDY2MzViODdmZjAiLCJnaXZlbl9uYW1lIjoiQW1pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsImp0aSI6IjA5ZGZhOGM0LTVhMTctNGFiYS04ODU4LWVmNmNhMmVlYTc1YyIsImV4cCI6MTY2OTU2Mzk2NSwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.QHc0XuyiBz8Lmg-nCxH21MZVng-c3W0OAua9H9zDtbE